scp averagejacard.py abe@shorty.cs.uno.edu:/home/abe/thesis/word2vec
scp counter_cumulative.py abe@shorty.cs.uno.edu:/home/abe/thesis/word2vec
scp grand_totaler.sh abe@shorty.cs.uno.edu:/home/abe/thesis/word2vec
scp counter.py abe@shorty.cs.uno.edu:/home/abe/thesis/word2vec
scp test_all.sh abe@shorty.cs.uno.edu:/home/abe/thesis/word2vec
scp test_k.sh abe@shorty.cs.uno.edu:/home/abe/thesis/word2vec
scp probability_calculator.py abe@shorty.cs.uno.edu:/home/abe/thesis/word2vec
scp probability_counter.sh abe@shorty.cs.uno.edu:/home/abe/thesis/word2vec
scp count_adjuster.py abe@shorty.cs.uno.edu:/home/abe/thesis/word2vec
scp wordnetchecker.py abe@shorty.cs.uno.edu:/home/abe/thesis/word2vec
scp main.sh abe@shorty.cs.uno.edu:/home/abe/thesis/word2vec
scp experiment.py abe@shorty.cs.uno.edu:/home/abe/thesis/word2vec
scp wordnetter.py abe@shorty.cs.uno.edu:/home/abe/thesis/word2vec
scp process_results.sh abe@shorty.cs.uno.edu:/home/abe/thesis/word2vec
scp type_counter.sh abe@shorty.cs.uno.edu:/home/abe/thesis/word2vec
scp total_counter.sh abe@shorty.cs.uno.edu:/home/abe/thesis/word2vec
scp scatterploy.py abe@shorty.cs.uno.edu:/home/abe/thesis/word2vec
scp plotmaker.sh abe@shorty.cs.uno.edu:/home/abe/thesis/word2vec
