scp count_adjuster.py abe@shorty.cs.uno.edu:/home/abe/thesis/word2vec
scp wordnetchecker.py abe@shorty.cs.uno.edu:/home/abe/thesis/word2vec
scp main.sh abe@shorty.cs.uno.edu:/home/abe/thesis/word2vec
scp experiment.py abe@shorty.cs.uno.edu:/home/abe/thesis/word2vec
scp wordnetter.py abe@shorty.cs.uno.edu:/home/abe/thesis/word2vec
scp process_results.sh abe@shorty.cs.uno.edu:/home/abe/thesis/word2vec
scp type_counter.sh abe@shorty.cs.uno.edu:/home/abe/thesis/word2vec
scp total_counter.sh abe@shorty.cs.uno.edu:/home/abe/thesis/word2vec
scp scatterploy.py abe@shorty.cs.uno.edu:/home/abe/thesis/word2vec
#scp chartmaker.py abe@shorty.cs.uno.edu:/home/abe/thesis/word2vec
#scp barcharter.py abe@shorty.cs.uno.edu:/home/abe/thesis/word2vec
